version: "3.9"
services:
  api:
    container_name: tactil_api
    build:
      dockerfile: docker/Dockerfile.api
      context: ..
    image: ghcr.io/owenbrooks/tactil-api
    ports:
      - "5000:5000"
    volumes:
      - ../:/tactil:rw
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev/dri:/dev/dri
    environment:
      - DISPLAY=$DISPLAY
  ui:
    container_name: tactil_ui
    depends_on:
      - api
    restart: always
    build:
      dockerfile: docker/Dockerfile.ui
      context: ..
    ports:
      - "80:3000"
    image: ghcr.io/owenbrooks/tactil-ui
