version: "3.9"
services:
  api:
    container_name: tactil_api
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    image: ghcr.io/owenbrooks/tactil-api
    ports:
      - "5000:5000"
    volumes:
      - ../:/tactil:rw
  nginx:
    depends_on:
      - api
    restart: always
    build:
      dockerfile: docker/nginx/Dockerfile
      context: ..
    ports:
      - "80:80"
